site_name: Maverick.EntityGraph Documentation
repo_url: https://github.com/bechtleav360/Maverick.EntityGraph

theme:
  name: material

plugins:
  - search




markdown_extensions:
  - admonition
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tabbed:
      alternate_style: true