## All XXX fields are provisioned through environment variables

application:
  security:
    api-key: "xxx"

  features:
    schedulers:
      detectDuplicates: false
      replaceGlobalIdentifiers: true
    transformers:
      replaceGlobalIdentifiers: true
      replaceAnonymousIdentifiers: true
      mergeDuplicates: true
    validators:
      checkRequiredType: true

  storage:
    vocabularies:
      persistent: true
      path: "/var/data/vocabularies"
    system:
      persistent: true
      path: "/var/data/system"
    entities:
      persistent: true
      path: "/var/data/entities"
    transactions:
      persistent: true
      path: "/var/data/transactions"


spring:
  security:
    user:
      name: "xxx"
      password: "xxx"





logging:
  file:
    name: server.log
  level:
    com:
      bechtle: INFO
    org:
      springframework:
        security: INFO

