#spring:
#  datasource:
#    url: jdbc:h2:file:/data/demo

application:
  security:
    enabled: true
    apiKey: "123"
    basic:
      enabled: false
  features:

    modules:
      objects:
        enabled: true
        configuration:
          mode: local
          path: "D:/Graphen/entities/objects"
      applications:
        enabled: true
        configuration:
          mode: remote

      admin:
        enabled: true
      jobs:
        enabled: true
        scheduled:
          detectDuplicates:
            enabled: true
          replaceIdentifiers:
            enabled: true
          typeCoercion:
            enabled: true
          exportApplication:
            enabled: true
            defaultLocalPath: "D:/Graphen/entities/exports"
      navigation:
        enabled: true
    transformers:
      replaceGlobalIdentifiers: true
      replaceAnonymousIdentifiers: true
      mergeDuplicates: true
      typeCoercion: true
    validators:
      checkRequiredType: true

  storage:
    remotes: ~

    defaults:
      - label: system
        persistent: true
        remote: false
        published: false
        config:
          path: "D:/Graphen/system"
      - label: vocabularies
        persistent: true
        remote: false
        published: true
        config:
          path: "D:/Graphen/vocabularies"
      - label: entities
        persistent: true
        remote: false
        published: true
        config:
          path: "D:/Graphen/entities"
      - label: transactions
        persistent: true
        remote: false
        published: true
        config:
          path: "D:/Graphen/transactions"


spring:
  security:
    user:
      name: "user"
      password: "123"

logging:
  file:
    name: "main.log"
    path: "D:/Graphen/"
  level:
    root: INFO
    graph:
      jobs: DEBUG
      repo: TRACE
      srvc: TRACE
      ctrl: DEBUG
      feat: TRACE
    org:
      eclipse:
        rdf4j: DEBUG
      springframework:
        security: INFO

