#spring:
#  datasource:
#    url: jdbc:h2:file:/data/demo

application:
  security:
    enabled: true
    apiKey: "123"
    basic:
      enabled: false
  features:
    modules:
      applications:
        enabled: true
      admin:
        enabled: true
      jobs:
        enabled: true
        scheduled:
          detectDuplicates:
            enabled: true
            defaultFrequency: "0 */5 * * * ?"
          replaceIdentifiers:
            enabled: true
            defaultFrequency: "0 */5 * * * ?"
          typeCoercion:
            enabled: true
            defaultFrequency: "0 */5 * * * ?"
          exportApplication:
            enabled: true
            defaultFrequency: "0 */5 * * * ?"
            defaultS3Host: "http://127.0.0.1:9000"
            defaultS3BucketId: "test"
      navigation:
        enabled: true
    transformers:
      replaceGlobalIdentifiers: true
      replaceAnonymousIdentifiers: true
      mergeDuplicates: true
      typeCoercion: true
    validators:
      checkRequiredType: true
#  storage:
#    vocabularies:
#      persistent: true
#      path: "C:/Graphen/vocabularies"
#    system:
#      persistent: true
#      path: "C:/Graphen/system"
#    entities:
#      persistent: true
#      path: "C:/Graphen/entities"
#    transactions:
#      persistent: true
#      path: "C:/Graphen/transactions"



logging:
  level:
    root: INFO
    graph:
      jobs: TRACE
      repo: TRACE
      srvc: TRACE
      ctrl: TRACE
      feat:
        admin: TRACE
    org:
      eclipse:
        rdf4j: DEBUG
      springframework:
        security: INFO

management:
  info:
    env:
      enabled: true
    git:
      enabled: true
      mode: full
  health:
    defaults:
      enabled: false
    probes:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "health, info, env, beans, git, loggers, metrics, scheduledTasks, logfile, mappings, prometheus"
  endpoint:
    discovery:
      enabled: true
    health:
      enabled: true
      show-details: always
    info:
      enabled: true
    env:
      enabled: true
    loggers:
      enabled: true
    metrics:
      enabled: true
    scheduledTasks:
      enabled: true
    logfile:
      enabled: true
    prometheus:
      enabled: true