#spring:
#  datasource:
#    url: jdbc:h2:file:/data/demo

application:
  security:
    enabled: true
    apiKey: "123"
    basic:
      enabled: false
  features:
    modules:
      applications:
        enabled: true
      admin:
        enabled: true
      jobs:
        enabled: true
        scheduled:
          detectDuplicates: true
          replaceIdentifiers: true
          typeCoercion: true
    transformers:
      replaceGlobalIdentifiers: true
      replaceAnonymousIdentifiers: true
      mergeDuplicates: true
      typeCoercion: true
    validators:
      checkRequiredType: true
  storage:
    default:
      persistent: true
      path: "D:/Graphen/default"
    entities:
      persistent: true
      path: "D:/Graphen/entities"
    transactions:
      persistent: true
      path: "D:/Graphen/transactions"

spring:
  security:
    user:
      name: "xxx"
      password: "xx"

logging:
  file:
    name: "main.log"
    path: "D:/Graphen/"
  level:
    graph:
      jobs: TRACE
      repo: TRACE
      srvc: TRACE
      ctrl: TRACE


    org:
      springframework:
        security: INFO

