#spring:
#  datasource:
#    url: jdbc:h2:file:/data/demo

application:
  security:
    enabled: true
    apiKey: "123"
    basic:
      enabled: false
  features:
    modules:
      applications: false
      admin: true
    schedulers:
      detectDuplicates: false
      replaceGlobalIdentifiers: false
    transformers:
      replaceGlobalIdentifiers: true
      replaceAnonymousIdentifiers: true
      mergeDuplicates: true
    validators:
      checkRequiredType: true
  storage:
    default:
      persistent: false
      path: ~
    entities:
      persistent: false
      path: ~
    transactions:
      persistent: false
      path: ~



logging:
  level:
    graph: TRACE
    org:
      springframework:
        security: INFO

