#spring:
#  datasource:
#    url: jdbc:h2:file:/data/demo

application:
  security:
    enabled: true
    apiKey: "123"
    basic:
      enabled: false
  features:

    modules:
      objects:
        enabled: true
        configuration:
          mode: local
          path: "D:/Graphen/entities/objects"
      applications:
        enabled: true
      admin:
        enabled: true
      jobs:
        enabled: true
        scheduled:
          detectDuplicates:
            enabled: true
          replaceIdentifiers:
            enabled: true
          typeCoercion:
            enabled: true
          exportApplication:
            enabled: true
            defaultLocalPath: "D:/Graphen/entities/exports"
      navigation:
        enabled: true
    transformers:
      replaceGlobalIdentifiers: true
      replaceAnonymousIdentifiers: true
      mergeDuplicates: true
      typeCoercion: true
    validators:
      checkRequiredType: true
  storage:
    vocabularies:
      persistent: true
      path: "D:/Graphen/vocabularies"
    system:
      persistent: true
      path: "D:/Graphen/system"
    entities:
      persistent: true
      path: "D:/Graphen/entities"
    transactions:
      persistent: true
      path: "D:/Graphen/transactions"

spring:
  security:
    user:
      name: "xxx"
      password: "xx"

logging:
  file:
    name: "main.log"
    path: "D:/Graphen/"
  level:
    root: INFO
    graph:
      jobs: DEBUG
      repo: TRACE
      srvc: TRACE
      ctrl: DEBUG
      feat: TRACE
    org:
      eclipse:
        rdf4j: DEBUG
      springframework:
        security: INFO

