{ { - if .Values.persistence.enabled } }
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: { { .Release.Name } }-pvc-entities
  namespace: { { .Release.Namespace } }
  labels:
    { { - include "template.labels" . | nindent 4 } }
spec:
  accessModes:
    - { { .Values.persistence.accessMode | quote } }
  resources:
    requests:
      storage: { { .Values.persistence.entities.size | quote } }
  { { - end } }